name: fashin_play
description: "FASHIN Play - A simple mobile music player."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Audio
  just_audio: ^0.9.36
  audio_service: ^0.18.12

  # Tools
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2

  # Parsing HTTP
  http: ^1.0.0

  # UI
  google_fonts: ^6.1.0

  # Youtube Parser
  youtube_explode_dart: ^2.5.0

  # Utilities
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/